#!/bin/bash
TOKEN=$(curl -s http://127.0.0.1:4200/api/v1/auth/login -X POST -H 'Content-Type: application/json' -d @/tmp/login.json | grep -o '"token":"[^"]*"' | cut -d'"' -f4)
echo "Token: ${TOKEN:0:20}..."
echo ""
echo "=== Testing APIs ==="
echo -n "Users: "; curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4200/api/v1/users -H "Authorization: Bearer $TOKEN"
echo ""
echo -n "Leads: "; curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4200/api/v1/leads -H "Authorization: Bearer $TOKEN"
echo ""
echo -n "Opportunities: "; curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4200/api/v1/opportunities -H "Authorization: Bearer $TOKEN"
echo ""
echo -n "Contacts: "; curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4200/api/v1/contacts -H "Authorization: Bearer $TOKEN"
echo ""
echo -n "Tasks: "; curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4200/api/v1/tasks -H "Authorization: Bearer $TOKEN"
echo ""
echo -n "Interactions: "; curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4200/api/v1/interactions -H "Authorization: Bearer $TOKEN"
echo ""
echo -n "Workflows: "; curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4200/api/v1/workflows -H "Authorization: Bearer $TOKEN"
echo ""
echo -n "Teams: "; curl -s -o /dev/null -w '%{http_code}' http://127.0.0.1:4200/api/v1/users/teams -H "Authorization: Bearer $TOKEN"
echo ""
echo ""
echo "=== Sample Response (Leads) ==="
curl -s http://127.0.0.1:4200/api/v1/leads -H "Authorization: Bearer $TOKEN" | head -c 300
echo ""
